// <auto-generated />
namespace ContosoUniversity.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class Fix20 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Fix20));
        
        string IMigrationMetadata.Id
        {
            get { return "201611021806139_Fix20"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
